### ISSUE TITLE
Player Automatically Accepts Invitation When Push Notification Selected

### ISSUE THREAD

**Issue by alexandertape** [mhatzitaskos/TurnBasedSkeleton#1]
I am using your repository for a project of mine, and I am observing the following behavior:

In a game created with a specific opponent to invite, after the first turn is sent, the opponent player receives two push notifications simultaneously: first, a 'Game Center Invitation', then a 'Game Center Turn'. If one of the two push notifications is touched, the app is entered and the invite is accepted. If I launch the app manually, the game properly appears in "Invited by opponent".

This could be something I'm doing wrong, but I have yet to find the solution and was wondering if this is being observed by yourself as well. 

Is there a specific method called when the user selects one of these push notifications? Maybe I'm just not handling properly.

Any information would be appreciated, even if it's just that I'm doing something wrong. Thanks!

**Comment by mhatzitaskos** [comment]
In the `func playFirstTurn(match: GKTurnBasedMatch)` there is a sendReminder method called:
`GameCenterSingleton.sharedInstance.sendReminder(match, completion: {
                _ in
            })
`
If you remove that it should fix the problem.
GameCenter does not always inform the opponent for the new game and `sendReminder` was a hack to allow for the opponent to receive the notification.

I've also updated the project to reflect this change.

**Comment by alexandertape** [comment]
Thank you for your response.

Removing the line you suggested prevents the second push notification, but I am still seeing that issue that selecting the push notification for the Invitation launches the game and automatically accepts the invite. Are you observing this yourself? The way the project is designed, I imagine selecting this push notification should open the app but still leave the match in the "Invited by opponent" state.

**Comment by mhatzitaskos** [comment]
I see what you're saying. Well, from my understanding, selecting the push notification is like accepting the invitation. I have no control over what method is called when the push notification is tapped. The method that accepts the invitation is automatically run by GameCenter. Thus, I suppose that this is indeed the intended behavior.

**Comment by alexandertape** [comment]
Okay, thank you! I consider the issue closed in that case. Thanks for this project, it has helped me a lot.
